# Generated by Django 5.2.2 on 2025-06-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_attachment_messagestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
